apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/monitoring
images:
  - name: nlp-api
    newName: ghcr.io/OWNER/nlp-k8s-platform    # <- replace OWNER with your GitHub username
    newTag: "1.0.0"
patches:
  - target: {kind: HorizontalPodAutoscaler, name: nlp-api}
    patch: |-
      - {op: replace, path: /spec/minReplicas, value: 3}
      - {op: replace, path: /spec/maxReplicas, value: 10}
  - target: {kind: Ingress, name: nlp-api}
    patch: |-
      - {op: replace, path: /spec/rules/0/host, value: nlp.example.com}
      - {op: add, path: /metadata/annotations/cert-manager.io~1cluster-issuer, value: letsencrypt-prod}
      - {op: add, path: /spec/tls, value: [{hosts: [nlp.example.com], secretName: nlp-api-tls}]}
  - target: {kind: Deployment, name: nlp-api}
    patch: |-
      - {op: replace, path: /spec/template/spec/topologySpreadConstraints/0/whenUnsatisfiable, value: DoNotSchedule}
